name: package_playground
description: "Test playground for feature_flag_audit package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  feature_flag_audit:
    git:
      url: https://github.com/NJashwanth/feature_flag_audit.git
      ref: feat/pipeline-policy
  googleapis_auth: ^2.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
